con_0day_mean <- mean(Mouse_weight$Control[1:9],na.rm = TRUE);con_0day_se <- sd(Mouse_weight$Control[1:9],na.rm = TRUE)/sqrt(9)
con_4day_mean <- mean(Mouse_weight$Control[10:17],na.rm = TRUE);con_4day_se <- sd(Mouse_weight$Control[10:17],na.rm = TRUE)/sqrt(9)
con_8day_mean <- mean(Mouse_weight$Control[18:25],na.rm = TRUE);con_8day_se <- sd(Mouse_weight$Control[18:25],na.rm = TRUE)/sqrt(9)
con_12day_mean <- mean(Mouse_weight$Control[26:33],na.rm = TRUE);con_12day_se <- sd(Mouse_weight$Control[26:33],na.rm = TRUE)/sqrt(9)
con_16day_mean <- mean(Mouse_weight$Control[34:41],na.rm = TRUE);con_16day_se <- sd(Mouse_weight$Control[34:41],na.rm = TRUE)/sqrt(9)
con_20day_mean <- mean(Mouse_weight$Control[42:49],na.rm = TRUE);con_20day_se <- sd(Mouse_weight$Control[42:49],na.rm = TRUE)/sqrt(9)
con_28day_mean <- mean(Mouse_weight$Control[50:57],na.rm = TRUE);con_28day_se <- sd(Mouse_weight$Control[50:57],na.rm = TRUE)/sqrt(9)
con_35day_mean <- mean(Mouse_weight$Control[58:65],na.rm = TRUE);con_35day_se <- sd(Mouse_weight$Control[58:65],na.rm = TRUE)/sqrt(9)
treat_0day_mean <- mean(Mouse_weight$Treatment[1:9],na.rm = TRUE);treat_0day_se <- sd(Mouse_weight$Treatment[1:9])/sqrt(9)
treat_4day_mean <- mean(Mouse_weight$Treatment[10:17],na.rm = TRUE);treat_4day_se <- sd(Mouse_weight$Treatment[10:17])/sqrt(9)
treat_8day_mean <- mean(Mouse_weight$Treatment[18:25],na.rm = TRUE);treat_8day_se <- sd(Mouse_weight$Treatment[18:25])/sqrt(9)
treat_12day_mean <- mean(Mouse_weight$Treatment[26:33],na.rm = TRUE);treat_12day_se <- sd(Mouse_weight$Treatment[26:33])/sqrt(9)
treat_16day_mean <- mean(Mouse_weight$Treatment[34:41],na.rm = TRUE);treat_16day_se <- sd(Mouse_weight$Treatment[34:41])/sqrt(9)
treat_20day_mean <- mean(Mouse_weight$Treatment[42:49],na.rm = TRUE);treat_20day_se <- sd(Mouse_weight$Treatment[42:49])/sqrt(9)
treat_28day_mean <- mean(Mouse_weight$Treatment[50:57],na.rm = TRUE);treat_28day_se <- sd(Mouse_weight$Treatment[50:57])/sqrt(9)
treat_35day_mean <- mean(Mouse_weight$Treatment[58:65],na.rm = TRUE);treat_35day_se <- sd(Mouse_weight$Treatment[58:65])/sqrt(9)
weight_data <- data.frame(post_treatment_initiation=c(0,4,8,12,16,20,28,35),weight=c(con_0day_mean,con_4day_mean,con_8day_mean,con_12day_mean,con_16day_mean,con_20day_mean,con_28day_mean,con_35day_mean,treat_0day_mean,treat_4day_mean,treat_8day_mean,treat_12day_mean,treat_16day_mean,treat_20day_mean,treat_28day_mean,treat_35day_mean),se=c(con_0day_se,con_4day_se,con_8day_se,con_12day_se,con_16day_se,con_20day_se,con_28day_se,con_35day_se,treat_0day_se,treat_4day_se,treat_8day_se,treat_12day_se,treat_16day_se,treat_20day_se,treat_28day_se,treat_35day_se),group=rep(c("con","treat"),each=8))
p <- ggplot(data = weight_data,mapping = aes(x=weight_data$post_treatment_initiation,y=weight_data$weight,group=weight_data$group,color=group))
p+geom_line(size=0.75)+geom_point(size=2)+theme_classic()+geom_errorbar(aes(ymax=weight_data$weight+weight_data$se,ymin=weight_data$weight-weight_data$se),size=0.75)+xlab("Treatment Day")+ylab("Average Weight (g)")+scale_color_manual(values = cbPalette)
